version: '3.8'

services:
  server1:
    build:
      context: ./server1
    ports:
      - "3001:3000"
    networks:
      - prometheus_network

  server2:
    build:
      context: ./server2
    ports:
      - "3002:3000"
    networks:
      - prometheus_network

  server3:
    build:
      context: ./server3
    ports:
      - "3003:3000"
    networks:
      - prometheus_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prometheus_network

networks:
  prometheus_network:
    driver: bridge
