global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'server1'
    static_configs:
      - targets: ['server1:3000']

  - job_name: 'server2'
    static_configs:
      - targets: ['server2:3000']

  - job_name: 'server3'
    static_configs:
      - targets: ['server3:3000']
