global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server1'
    static_configs:
      - targets: ['server1:3000']

  - job_name: 'server2'
    static_configs:
      - targets: ['server2:3000']

  - job_name: 'server3'
    static_configs:
      - targets: ['server3:3000']

  - job_name: 'dynamic'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert.rules.yml
